language: node_js
node_js:
  - 13

services:
  - docker

script: 
  - docker build -t udagram-api-feed ./udagram-api-feed

  - docker build -t udagram-api-user ./udagram-api-user

  - docker build -t reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed tibbsdocker/udagram-api-feed:v1

  - docker tag udagram-api-user tibbsdocker/udagram-api-user:v1

  - docker tag reverseproxy tibbsdocker/reverseproxy:v1

after_success: 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push tibbsdocker/udagram-api-feed:v1

  - docker push tibbsdocker/udagram-api-user:v1

  - docker push tibbsdocker/reverseproxy:v1